### ISSUE TITLE
[Tracking] SMask regressions from PR 4161

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#7011]
_This issue is intended to help track various SMask related regressions from PR #4161._
- [x] [Issue 6165](https://github.com/mozilla/pdf.js/issues/6165) - Bad render of sec-guide-to-proxy-brochures
- [ ] [Issue 6967](https://github.com/mozilla/pdf.js/issues/6967) - Image in PDF doesn't load
- [x] [Issue 7143](https://github.com/mozilla/pdf.js/issues/7143) - Some images are not rendered correctly/at all
- [ ] [Bug 852992](https://bugzilla.mozilla.org/show_bug.cgi?id=852992) - [PDF Viewer] Image pattern not rendered
- [x] [Bug 1199237](https://bugzilla.mozilla.org/show_bug.cgi?id=1199237) - Wrong rendering by the FF built-in viewer of a PDF file correctly rendered with external PDF viewers

---

**Note:** This is a tracking bug, please _do not_ post unrelated comments here!

**Comment by Snuffleupagus** [comment]
The problem with all of the PDF files in the referenced issues/bugs is that they are fairly complex, thus making debugging much more difficult.
Hence I've tried to create a reduced test-case, see below, by manually removing/simplifying as much as possible in one of the PDF files (I hope that it still exhibits the same problem as original file).

[bug852992_reduced.pdf](https://github.com/mozilla/pdf.js/files/206591/bug852992_reduced.pdf)

**Comment by yurydelendik** [comment]
> I hope that it still exhibits the same problem as the original file.
> bug852992_reduced.pdf

It is not. But I have a fix for this particular case:


```diff
diff --git a/src/display/canvas.js b/src/display/canvas.js
index 5df5a73..4a04acc 100644
--- a/src/display/canvas.js
+++ b/src/display/canvas.js
@@ -869,6 +869,11 @@ var CanvasGraphics = (function CanvasGraphicsClosure() {
     },
 
     endDrawing: function CanvasGraphics_endDrawing() {
+      // Finishing all opened operations such as SMask group painting.
+      if (this.current.activeSMask !== null) {
+        this.endSMaskGroup();
+      }
+
       this.ctx.restore();
 
       if (this.transparentCanvas) {
```

**Comment by yurydelendik** [comment]
#6967 is a weird one and looks like PDF.js is doing a right thing (?): mask is painted outside of page and when applied it hides the content painted on the page/

**Comment by yurydelendik** [comment]
Bug 852992 contains two different issue, addressing the regression only

**Comment by yurydelendik** [comment]
Let's keep Bug 852992 as unaddressed since http://martin.von-gagern.net/publications/2008-diploma/Diplomarbeit.pdf p.74 shows similar problem as Issue 6967

**Comment by timvandermeij** [comment]
Closing since the mentioned problems are either fixed, won't-fix or have a dedicated issue, so there is no need for this tracking issue anymore.
