### ISSUE TITLE
Tracking issue for bot problems

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#8029]
Note that these problems may or may not be related to recent bot updates.

- [x] Development add-on (XPI) is not signed anymore (perhaps `unzip` is missing on the bots, as that process is being spawned?)
- [x] Linux bot appears to be dead (see https://github.com/mozilla/pdf.js/pull/8028#issuecomment-277520822)
- [ ] Issue #8005
- [x] Issue #8015 
- [x] IRC shows `pdf.js/gh-pages b269a97 Brendan Dahl: gh-pages site created via make.js script...` instead of pdfjsbot

**Comment by yurydelendik** [comment]
> Development add-on (XPI) is not signed anymore

yeah, maybe unzip or path to it, or @brendandahl do you still have amo.json file from old windows bot? on_push still has signxpi.js call https://github.com/mozilla/botio-files-pdfjs/blob/master/on_push.js#L23

**Comment by brendandahl** [comment]
unzip is there. I didn't copy over amo.json (fixed now).

**Comment by brendandahl** [comment]
Git user should be fixed now too.

**Comment by timvandermeij** [comment]
Closing as fixed. The remaining problem is tracked in a separate issue. Thanks!
